classe webcam
nwoki/udevnotifier pull request #2
Opened 2017-02-27 15:27 UTC by Elvisnando

2017-02-27 15:31 UTC, nwoki commented on lib/webcam.h
> +#include <libudev.h>
double include

2017-02-27 15:31 UTC, nwoki commented on lib/device.h
> +#include <QtCore/QThread>
why?

2017-02-27 15:32 UTC, nwoki commented on lib/device.h
> +#include <QtCore/QThread>
why?

2017-02-27 15:32 UTC, nwoki commented on lib/device.h
> +    enum TIPO{
eng please

2017-02-27 15:33 UTC, nwoki commented on lib/device.h
> +        WEBCAM
what happens if it's not any of the above?

2017-02-27 15:34 UTC, nwoki commented on lib/device.h
> +    TIPO   Typedevice();
"camelCase" please

2017-02-27 15:34 UTC, nwoki commented on lib/device.h
> +
extra space for nothing

2017-02-27 15:34 UTC, nwoki commented on lib/lib.pro
> +    webcam.h\
alphabetical order

2017-02-27 15:35 UTC, nwoki commented on lib/monitor.cpp
> +
extra space for nothing

2017-02-27 15:35 UTC, nwoki commented on lib/monitor.cpp
> +    qDebug() << "qyesto è un monitr";
don't need this

2017-02-27 15:35 UTC, nwoki commented on lib/monitor.cpp
> +#include <QtCore/QDebug>
don't need

2017-02-27 15:35 UTC, nwoki commented on lib/monitor.cpp
> +
extra space for nothing

2017-02-27 15:35 UTC, Elvisnando commented on lib/device.h
> +#include <QtCore/QThread>
era solo una prova elimino

2017-02-27 15:36 UTC, nwoki commented on lib/webcam.cpp
> +    qDebug()<<"Questa è una web cam";
do not need

2017-02-27 15:36 UTC, nwoki commented on lib/webcam.cpp
> +#include <QtCore/QDebug>
do not need

2017-02-27 15:36 UTC, nwoki commented on lib/webcam.h
> +
extra space for nothing

2017-02-27 15:40 UTC, nwoki commented on lib/device.cpp
> +    if(d->subsystem=="video4linux"){
why use type on one if and subsystem on the other?

2017-02-27 15:58 UTC, Elvisnando commented on lib/device.cpp
> +    if(d->subsystem=="video4linux"){
perche il in tybe mi dice che è un usb   generico con il susystem rilevo  video4linux

2017-02-27 16:00 UTC, Elvisnando commented on lib/device.h
> +        WEBCAM
ritorna -256 come valore

2017-02-27 16:11 UTC, nwoki commented on lib/device.cpp
> +    if(d->subsystem=="video4linux"){
* fix code indentation

2017-02-27 16:11 UTC, nwoki commented on lib/device.h
> +
again: what if it's none of these two types?

2017-02-27 16:11 UTC, nwoki commented on lib/device.h
> +    TYPE   Typedevice();
camelCase pls

2017-02-27 16:12 UTC, nwoki commented on lib/device.cpp
> +
extra space for nothing

2017-02-28 16:00 UTC, nwoki commented on lib/device.h
> +    enum TYPE {
DeviceType

2017-02-28 16:00 UTC, nwoki commented on lib/device.h
> +    Device(udev_device *device = nullptr, TYPE typeD  = USBDEVICE);
deviceType

2017-02-28 16:01 UTC, nwoki commented on lib/device.h
> +    TYPE tDevice();
deviceType

2017-02-28 16:01 UTC, nwoki commented on lib/device.h
> +    TYPE typeDevice;
deviceType

2017-02-28 16:01 UTC, nwoki commented on lib/monitor.cpp
> +    :Device(device,MONITOR)
spacing

2017-02-28 16:01 UTC, nwoki commented on lib/webcam.cpp
> +    :Device(device,WEBCAM)
spacing

2017-02-28 16:01 UTC, nwoki commented on lib/device.cpp
> +    this->typeDevice=typeD;
this is implicit

2017-02-28 16:01 UTC, nwoki commented on lib/device.cpp
> +        qDebug() << "TIPO :" << tDevice();
change

2017-02-28 16:02 UTC, nwoki commented on lib/device.cpp
> +Device::TYPE Device::tDevice()
change -> deviceType and make is a const reference

2017-02-28 16:02 UTC, nwoki commented on lib/device.cpp
> +return typeDevice;
indent

2017-02-28 16:24 UTC, nwoki commented on lib/device.cpp
> +Device::Device(udev_device* device, TYPEDEVICE typeD)
DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType

2017-02-28 16:25 UTC, nwoki commented on lib/device.cpp
> +    typeDevice=typeD;
spacing

2017-02-28 16:25 UTC, nwoki commented on lib/device.h
> +    enum TYPEDEVICE {
DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType DeviceType

2017-03-01 08:42 UTC, nwoki commented on lib/device.cpp
> +Device::Device(udev_device* device, DeviceType deviceT )
deviceT -> deviceType

2017-03-01 08:42 UTC, nwoki commented on lib/device.cpp
> +    typeDevice = deviceT;
same here. deviceType

2017-03-01 08:43 UTC, nwoki commented on lib/device.cpp
> +        qDebug() << "TIPO :" << deviceType();
no italian. Only eng

2017-03-01 08:43 UTC, nwoki commented on lib/device.cpp
> +
remove whitespace

2017-03-01 08:43 UTC, nwoki commented on lib/device.cpp
> +    return typeDevice;
var name

2017-03-01 08:43 UTC, nwoki commented on lib/device.h
> +    Device(udev_device *device = nullptr, DeviceType deviceType  = USBDEVICE);
careful, extra space here

2017-03-01 08:44 UTC, nwoki commented on lib/device.h
> +    DeviceType typeDevice;
device type

2017-03-01 08:44 UTC, nwoki commented on lib/device_p.h
> +
extra space not needed

2017-03-01 08:45 UTC, nwoki commented on lib/udevnotifier.cpp
> +#include"webcam.h"
space

2017-03-01 08:46 UTC, nwoki commented on lib/udevnotifier.cpp
> +          //  Q_EMIT udevEvent(actionFromString(udev_device_get_action(dev)), new Device(dev));
if you don't use it, remove it

2017-03-01 08:52 UTC, Elvisnando commented on lib/device.cpp
> +Device::Device(udev_device* device, DeviceType deviceT )
ok, but name of function "deviceType" become "deviceTypeReturn"

2017-03-02 18:04 UTC, nwoki commented on lib/device.cpp
> +        qDebug() << "TYPE :" << Device::deviceType(); // Test funtion
no need to specify "Device::". The base class function will be automatically called

2017-03-02 18:05 UTC, nwoki commented on lib/device.h
> +    enum DataType {
it's not a DataType, but a DeviceType

2017-03-02 18:06 UTC, nwoki requested changes
Almost there. Fix the comments i added and then you're good to go

2017-03-13 13:49 UTC, nwoki approved these changes

2017-03-13 13:49 UTC, merged